language: c
dist: bionic

jobs:
  include:
    - stage: Tests
      name: "Linux"
      os: linux
      dist: bionic
      addons:
        apt:
          sources: &sources
            - sourceline: 'ppa:dciabrin/ngdevkit'
          packages:
            - emudbg-dev
            - autoconf-archive
            - libsdl2-dev
            - libglew-dev
      env:
      - BUILD_PARAMS=""
      - PREFIX="/usr"
      - PKGDATADIR="/usr/share/ngdevkit-gngeo"
    - name: "Windows cross-compiled"
      os: linux
      dist: bionic
      addons:
        apt:
          sources: *sources
          packages:
            - emudbg-dev
            - autoconf-archive
            - libsdl2-dev
            - mingw-w64
            - libz-mingw-w64-dev
      env:
      - BUILD_PARAMS="--host=x86_64-w64-mingw32 --enable-mingw"
      - WINDEPS="/tmp/deps"
      - PREFIX="/tmp/win"
      - PKGDATADIR="/tmp/win/share"
      - EXTRA_SETUP="unset CC"
      - SDL="https://www.libsdl.org/release/SDL2-devel-2.0.8-mingw.tar.gz"
      - GLEW="https://downloads.sourceforge.net/project/glew/glew/2.1.0/glew-2.1.0-win32.zip"

    - stage: Daily packages
      if: branch = ngdevkit
      name: Launchpad - deb
      before_script: skip
      script: skip
      deploy:
        provider: launchpad
        slug: "~dciabrin/ngdevkit/+git/gngeo"
        on:
          branch: ngdevkit
        oauth_token:
          secure: "0ScYr2l0WFM1aaqfnpSG8nNNKiJ2TSurgoYS4tccBqqKXbBQj8HQi5P384wz0BI6uKTz5mSIZk9Su4J8TtjA+6b7LsCsyoe9PVBUWXdbdPIOrA7tHb7Rz5WzZ1dV7V7hKKSAURnPKC6MfYL7QOMnnGg9YtnBga+G+LFmd6Zhr2DlG2Yv9UVqgW4D6HAuKKWxYU9KVh9ECw26K8No8Ah+YhqGDP6rmP0tzW446JqpbkAUD+39aKL/znDr7RWaNVmnG2/SHJJLx3HKEEeAaSBoozvz0GxTIkSKImwU3j1II2we2qKiQubdxK9lWwNt/flwEJbFHknI2/uhD0wLc7Fyjcv5QV3LlNhA3xBct6I4PvSf6fzUHEpbHBDFt2u7shDekvPHjlGCbcDd57kd0TJRFInFuDTj2YTp13WNVQ92L7uczR12UD9ZEhiARnG3ydKYdXNDFR0oXTSxmOLyKnv3PnQljrio7YXD8ezTJCzKMBOfprvAn4SGMKzEBfxhwlqRneY1/ywqutVe4fmgd65Z4Fyu2jnRRI4vOtDUPiLxJMR/WpvJNul4IHhmHjqD+xjNkFnmA980fR5U9ZEv/ZXdSReNh0PhjZV9K5S4V2wBBpg7pdQoAoyz7eVBJrwHvo9nVD3W7kmWwkJPo+ZPWFGY5Ug766l7vRkkMmwIqSWhAN4="
        oauth_token_secret:
          secure: "OtiZxKgxD1ozisFg5TUi77lW2jC/p/dtHso/VVA6yRM3BICsmIexOfkB7eOiq+3P8awRy2E2zNoKT2dcro1ywHE4M5FTvKC5o8l7tOhZ/mv8+X0xs1lUFxhD+Qzxhk/0lu00sPRGKucgIF/XODtxlxv36N0S1ytRI4UNMVqcJ//2tjqmEcJwHltr83T51iezjnFPleyvmswPnP8aiXB2gyHHV7HRf9/bzQqDtEtfq2Tq3wrOX4YQcI9+QJWAsWrhexhWkLktDcZR0wiCWbsnXm3h8sxZbRF2lJmV5a+z5ZTqFL8gVe9xgEtwf8xxkSUuiTGLuNtfqPDcbbb4bUDOHWa9K6Zznpn9mk1zDkrUtKuA5ZTCOzX670HnxJvFPsJXm9i9qwGrHGomzft34BOFDte/3eoeibohfRxbDGA4p9yqLROPNyg5C7B47H5NmUJLzHx9ZQCqHDEN2EFDQHUqUE6Wq08tHaSS10KP/RpaX2TMkuiOVBs3Zda0ScOqp/hV3i+y/IT+4f1/sm7WW2CfSttrvcieMGo4drmK85QhGAiXhJu9zaD92dxFkuelxyQXhIcuB0kRZ9axxLXFbtLTh2UgX0paciL7YYdN1f/rOyGyMuFxTjl89UDqfd9wslpxuTKNCWwHp7CpJzxwtbJDNLOXN2ZVY15TM+XM5bJ+BnY="

before_script:
  - if [ -n "$WINDEPS" ]; then mkdir -p $WINDEPS; cd $WINDEPS; fi
  - if [ -n "$SDL" ]; then curl -L "$SDL" | tar zx; sudo cp -af SDL2-*/*-mingw32 /usr/local; fi
  - if [ -n "$GLEW" ]; then curl -LO "$GLEW"; unzip $(basename "$GLEW"); fi

script:
  - cd $TRAVIS_BUILD_DIR
  - autoreconf -iv
  - if [ -n "$GLEW" ]; then EXTRA_PARAMS+=" --with-glew="$(find ${WINDEPS} -name 'glew*' -type d); fi
  - eval "$EXTRA_SETUP"
  - ./configure $BUILD_PARAMS --prefix=$PREFIX --program-prefix=ngdevkit- CFLAGS='-DGNGEORC=\"ngdevkit-gngeorc\"' $EXTRA_PARAMS
  - make pkgdatadir=$PKGDATADIR
  - sudo make install pkgdatadir=$PKGDATADIR
