language: c
dist: bionic

# Do not run on tag creation (e.g. skip tag created for nightly builds)
if: tag IS blank

# share the build output between stages
cache:
  directories: /tmp/build

env:
  global:
    secure: "YTWnFE4Ra0L8r/PVlcJC6sCeO7EKDnv8r41X5fUl7z3ie7M5qFNXnaXRRiXOHN1qDK6JsmOLGDzFHCM35fioSRrwMaJi9iNwuGx/l1M8kx5nqBpX9XTJfKlEyvdi3IRib+sP3RcQCa1Wdvpb6Rj9d+AUqIuJ3+gAXEkBRgW31LJuR91tSO836F8WcRcc8PdkWgC9WGWaKa5gCG+WGh0lHPI5L2a4LoI9WTiaRCpYMgip900frosqJBaaX9R5TOcf6Db46rXze9MbS8+AoaOZ6GbZ9hB/yb+Ck2WCB5rhYyGVix0j+AHJTSt9cWMsYXD4QdPUIM+NFXUNYFpSRNfUGWxJZY9RpdAheLSmRgX6jlc2iy84SCI4sxC92uP1pFangtm9Qi8mVy0xTxWdHWlJ0tfHabbaNoP8YvlSM7GghZfFFBdvX/VP4PJNU8So6Rt+M4BJofxVYPjerIa5tLwSVMuqFsLZz/lXXxc7QDzhJ9NINs0FZt+th5CNJ0pQi/ehRZRWkpJGZqa4tBE2cQ75AtLo20O/YKyQqWYXj0gBgAZ5ZK8SAudM2d9sgsUEoQpwJVjfsXJmsnNcox0xNfMg/bgdyX5MB/vA9ZB6tPK8LkDa+pig5SyKsnVESjegEHHwSzTcGBrckJvdUQ6a7I2lPjjswNCVN4spleYUdJqKhWY="

jobs:
  include:
    - stage: Tests
      name: Linux
      os: linux
      addons:
        apt:
          sources: &sources
            - sourceline: ppa:dciabrin/ngdevkit
          packages:
            - emudbg-dev
            - autoconf-archive
            - libsdl2-dev
            - libglew-dev
      env:
      - PREFIX="/tmp/build/linux"
      - PKGDATADIR="$PREFIX/share/ngdevkit-gngeo"
      script:
        - cd $TRAVIS_BUILD_DIR
        - autoreconf -iv
        - ./configure $BUILD_PARAMS --prefix=$PREFIX --program-prefix=ngdevkit- CFLAGS='-DGNGEORC=\"ngdevkit-gngeorc\"' $EXTRA_PARAMS
        - make pkgdatadir=$PKGDATADIR
        - make install pkgdatadir=$PKGDATADIR
    - name: Windows cross-compiled
      os: linux
      addons:
        apt:
          sources: *sources
          packages:
            - autoconf-archive
            - libsdl2-dev
            - mingw-w64
            - libz-mingw-w64-dev
            - emudbg-mingw-w64-dev
            - nsis
      env: &winenv
      - PREFIX="/tmp/build/win"
      - PKGDATADIR="$PREFIX/share"
      - WINDEPS="/tmp/deps"
      - SDL="https://www.libsdl.org/release/SDL2-devel-2.0.8-mingw.tar.gz"
      - GLEW="https://downloads.sourceforge.net/project/glew/glew/2.1.0/glew-2.1.0-win32.zip"
      - NSIS_SDL2="http://libsdl.org/release/SDL2-2.0.10-win32-x64.zip"
      - NSIS_GLEW="http://downloads.sourceforge.net/project/glew/glew/2.1.0/glew-2.1.0-win32.zip"
      script:
        - mkdir -p $WINDEPS; cd $WINDEPS
        - curl -L "$SDL" | tar zx; sudo cp -af SDL2-*/*-mingw32 /usr/local
        - curl -LO "$GLEW"; unzip $(basename "$GLEW")
        - cd $TRAVIS_BUILD_DIR
        - autoreconf -iv
        - unset CC
        - ./configure --host=x86_64-w64-mingw32 --enable-mingw --prefix=$PREFIX --program-prefix=ngdevkit- CFLAGS='-DGNGEORC=\"ngdevkit-gngeorc\"' PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/lib/pkgconfig --with-glew=$(find ${WINDEPS} -name 'glew*' -type d)
        - make pkgdatadir=$PKGDATADIR
        - make install pkgdatadir=$PKGDATADIR
        - make -C nsis all SDL2_URL="$NSIS_SDL2" GLEW_URL="$NSIS_GLEW" INSTALLER_NAME=setup-ngdevkit-gngeo-nightly.exe && cp nsis/setup-ngdevkit-gngeo-nightly.exe nsis/setup-ngdevkit-gngeo-nightly.exe.sha256 $PREFIX
    - stage: Deploy
      name: Launchpad - daily deb package
      if: type = push AND branch = ngdevkit
      script: skip
      deploy:
        - provider: launchpad
          slug: "~dciabrin/ngdevkit/+git/gngeo"
          on:
            branch: ngdevkit
          oauth_token:
            secure: "0ScYr2l0WFM1aaqfnpSG8nNNKiJ2TSurgoYS4tccBqqKXbBQj8HQi5P384wz0BI6uKTz5mSIZk9Su4J8TtjA+6b7LsCsyoe9PVBUWXdbdPIOrA7tHb7Rz5WzZ1dV7V7hKKSAURnPKC6MfYL7QOMnnGg9YtnBga+G+LFmd6Zhr2DlG2Yv9UVqgW4D6HAuKKWxYU9KVh9ECw26K8No8Ah+YhqGDP6rmP0tzW446JqpbkAUD+39aKL/znDr7RWaNVmnG2/SHJJLx3HKEEeAaSBoozvz0GxTIkSKImwU3j1II2we2qKiQubdxK9lWwNt/flwEJbFHknI2/uhD0wLc7Fyjcv5QV3LlNhA3xBct6I4PvSf6fzUHEpbHBDFt2u7shDekvPHjlGCbcDd57kd0TJRFInFuDTj2YTp13WNVQ92L7uczR12UD9ZEhiARnG3ydKYdXNDFR0oXTSxmOLyKnv3PnQljrio7YXD8ezTJCzKMBOfprvAn4SGMKzEBfxhwlqRneY1/ywqutVe4fmgd65Z4Fyu2jnRRI4vOtDUPiLxJMR/WpvJNul4IHhmHjqD+xjNkFnmA980fR5U9ZEv/ZXdSReNh0PhjZV9K5S4V2wBBpg7pdQoAoyz7eVBJrwHvo9nVD3W7kmWwkJPo+ZPWFGY5Ug766l7vRkkMmwIqSWhAN4="
          oauth_token_secret:
            secure: "OtiZxKgxD1ozisFg5TUi77lW2jC/p/dtHso/VVA6yRM3BICsmIexOfkB7eOiq+3P8awRy2E2zNoKT2dcro1ywHE4M5FTvKC5o8l7tOhZ/mv8+X0xs1lUFxhD+Qzxhk/0lu00sPRGKucgIF/XODtxlxv36N0S1ytRI4UNMVqcJ//2tjqmEcJwHltr83T51iezjnFPleyvmswPnP8aiXB2gyHHV7HRf9/bzQqDtEtfq2Tq3wrOX4YQcI9+QJWAsWrhexhWkLktDcZR0wiCWbsnXm3h8sxZbRF2lJmV5a+z5ZTqFL8gVe9xgEtwf8xxkSUuiTGLuNtfqPDcbbb4bUDOHWa9K6Zznpn9mk1zDkrUtKuA5ZTCOzX670HnxJvFPsJXm9i9qwGrHGomzft34BOFDte/3eoeibohfRxbDGA4p9yqLROPNyg5C7B47H5NmUJLzHx9ZQCqHDEN2EFDQHUqUE6Wq08tHaSS10KP/RpaX2TMkuiOVBs3Zda0ScOqp/hV3i+y/IT+4f1/sm7WW2CfSttrvcieMGo4drmK85QhGAiXhJu9zaD92dxFkuelxyQXhIcuB0kRZ9axxLXFbtLTh2UgX0paciL7YYdN1f/rOyGyMuFxTjl89UDqfd9wslpxuTKNCWwHp7CpJzxwtbJDNLOXN2ZVY15TM+XM5bJ+BnY="
    - script: skip
      name: GitHub release - nightly Windows installer
      if: type = push AND branch = ngdevkit
      # the env must match the test's env to use the right cache
      env: *winenv
      before_deploy:
        # we have to force-tag this commit to push a nightly release
        - export HEAD_COMMIT_DATE=$(TZ=UTC git show --quiet --date='format-local:%Y%m%d%H%M' --format='%cd')
        - if ! (git tag | grep -wq "nightly-${HEAD_COMMIT_DATE}"); then
            git config --local user.name "CI tag bot";
            git config --local user.email "<>";
            git tag "nightly-${HEAD_COMMIT_DATE}";
          fi
      deploy:
        provider: releases
        api_key:
          secure: S+rsYs6puM0a+YnYtpwkdrAId3Bp/TpUjVIGTkmAdoXx/RHTpozYbiXICpR0yCUtw3c1GPNPD5R5hIMobmXswM6Ymgo0rj9GfBJFARuc2Nf1st0Qt2gfDoIGHXhknCSwknzvcUmsqmCjn3HzYpSr4N3hdkK7mQbQlg8ctgjAv3iULBAA5MqENSRFo+R6pIq9U43XVkeB3iFDTswLsqCH9/luWX8FyvJPw7VHt1nZDGrFYPytSJYT2uUqg5gHZ0XOYdoDS1tbAqqMjExTHB18DqYeDt4tOABY4ek47qNbfwXdGGkCeJSujfeAz8k/iq8Tr3xiccK9rdiga9bW2gahTtrEKETOPg0oUavwKGkNo5TrN1wdhQC/1XRb+1ZDWkh0wtoBr7kvadBnDXEhcUXx82bivJRqslQJF7KQq6iU3zqLBdtUzRLAle4uj0KiT/+YcRqicX4/oxLQcRuFog+RvGi5Tax7fH2TfoOkbZVuqOBeoWizOiOW5AnNmla2hpllPq10WSKqIZg7RnEbGcq7TU66l+P2MAby1HVgDz3l3+yuL4mbNc7M6H1kjgRADg4iHaOR59bSGVUkspicamgcoabDjVC7TNZt1JoPB9pn5UpI83fZ1a0y06AfB32uGk0PuBPXuIxJhpw5nyNHLqtT9vyWDGAfSFW2vbMgkjOdEvs=
        file:
          - $PREFIX/setup-ngdevkit-gngeo-nightly.exe
          - $PREFIX/setup-ngdevkit-gngeo-nightly.exe.sha256
        prerelease: true
        overwrite: true
        on:
          repo: dciabrin/gngeo
          branch: ngdevkit
    - name: Homebrew - bottle
      if: type = push AND branch = ngdevkit
      script:
        - git config --global user.name 'CI build bot'
        - git config --global user.email '<>'
        - git config --global url."https://api@github.com/".insteadOf "https://github.com/"
        - git clone https://github.com/dciabrin/homebrew-ngdevkit .travis/homebrew-ngdevkit
        - .travis/homebrew-ngdevkit/.travis/bump-project-nightly-build.sh ngdevkit-gngeo ngdevkit
    - stage: Post-deploy
      name: Clean up old nightly releases and tags
      addons:
        apt:
          packages:
            - jq
      script: cd .travis && ./github-gc.sh --token="$GH_TOKEN" --tag-regex='^nightly-[0-9]+$'
      if: type = push AND branch = ngdevkit
