name: Build and Test
on:
  push:
    branches-ignore:
      - 'ngdevkit'
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    env:
      BUILD_PARAMS: ""
      PREFIX: "/tmp/build/linux"
      PKGDATADIR: "$PREFIX/share/ngdevkit-gngeo"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:dciabrin/ngdevkit
          sudo apt-get update -y
          sudo apt-get install -y emudbg-dev autoconf-archive libsdl2-dev libglew-dev
      - name: Build
        run: ./.github/scripts/build.sh

  win:
    name: Windows cross-compiled
    runs-on: ubuntu-latest
    env:
      BUILD_PARAMS: "--host=x86_64-w64-mingw32 --enable-mingw"
      PREFIX: "/tmp/build/mingw"
      PKGDATADIR: "$PREFIX/share"
      WINDEPS: "/tmp/deps"
      SDL: "https://www.libsdl.org/release/SDL2-devel-2.0.8-mingw.tar.gz"
      GLEW: "https://downloads.sourceforge.net/project/glew/glew/2.1.0/glew-2.1.0-win32.zip"
      NSIS_SDL2: "http://libsdl.org/release/SDL2-2.0.10-win32-x64.zip"
      NSIS_GLEW: "http://downloads.sourceforge.net/project/glew/glew/2.1.0/glew-2.1.0-win32.zip"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dependencies
        run: |
          sudo add-apt-repository -y ppa:dciabrin/ngdevkit
          sudo apt-get update -y
          sudo apt-get install -y emudbg-dev autoconf-archive libsdl2-dev libglew-dev
          sudo apt-get install mingw-w64 libz-mingw-w64-dev emudbg-mingw-w64-dev nsis

      - name: Build
        run: |
          ./.github/scripts/build-mingw.sh

  macos:
    name: macOS
    runs-on: macos-latest
    env:
      BUILD_PARAMS: ""
      PREFIX: "/tmp/build/macos"
      PKGDATADIR: "$PREFIX/share/ngdevkit-gngeo"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew tap dciabrin/ngdevkit
          brew install emudbg automake autoconf-archive sdl2 glew

      - name: Build
        run: ./.github/scripts/build.sh
