name: Build and Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - 'ngdevkit'
    paths-ignore:
      - 'README*.md'
jobs:
  linux:
    name: "Linux build"
    runs-on: ubuntu-latest
    env:
      BUILD_PARAMS: ""
      PREFIX: "/tmp/build/linux"
      PKGDATADIR: "$PREFIX/share/ngdevkit-gngeo"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:dciabrin/ngdevkit
          sudo apt-get update -y
          sudo apt-get install -y emudbg-dev autoconf-archive libsdl2-dev libglew-dev
      - name: Build
        run: ./.github/scripts/build.sh

  win:
    name: "Windows native MSYS2 build"
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install:
            git autoconf autoconf-archive automake make
            mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-libtool
            mingw-w64-ucrt-x86_64-pkgconf mingw-w64-ucrt-x86_64-SDL2
            mingw-w64-ucrt-x86_64-glew

      - name: Install ngdevkit dependencies
        run: |
          echo -e "[ngdevkit]\nSigLevel = Optional TrustAll\nServer = https://dciabrin.net/msys2-ngdevkit/\$arch" >> /etc/pacman.conf
          pacman -Sy
          pacman -S --noconfirm mingw-w64-ucrt-x86_64-emudbg

      - name: Build
        run: ./.github/scripts/build-msys2.sh

  macos:
    name: "macOS build"
    runs-on: macos-latest
    env:
      BUILD_PARAMS: ""
      PREFIX: "/tmp/build/macos"
      PKGDATADIR: "$PREFIX/share/ngdevkit-gngeo"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew tap dciabrin/ngdevkit
          brew trust dciabrin/ngdevkit
          brew install emudbg automake autoconf-archive sdl2 glew

      - name: Build
        run: ./.github/scripts/build.sh
